/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AudioSelectionModal: typeof import('./src/components/AudioSelectionModal.vue')['default']
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BButtonGroup: typeof import('bootstrap-vue-next/components/BButton')['BButtonGroup']
    BCard: typeof import('bootstrap-vue-next/components/BCard')['BCard']
    BCardBody: typeof import('bootstrap-vue-next/components/BCard')['BCardBody']
    BCardImg: typeof import('bootstrap-vue-next/components/BCard')['BCardImg']
    BCardTitle: typeof import('bootstrap-vue-next/components/BCard')['BCardTitle']
    BCol: typeof import('bootstrap-vue-next/components/BContainer')['BCol']
    BForm: typeof import('bootstrap-vue-next/components/BForm')['BForm']
    BFormFile: typeof import('bootstrap-vue-next/components/BFormFile')['BFormFile']
    BFormGroup: typeof import('bootstrap-vue-next/components/BFormGroup')['BFormGroup']
    BFormSelect: typeof import('bootstrap-vue-next/components/BFormSelect')['BFormSelect']
    BFormSelectOption: typeof import('bootstrap-vue-next/components/BFormSelect')['BFormSelectOption']
    BFormTextarea: typeof import('bootstrap-vue-next/components/BFormTextarea')['BFormTextarea']
    BImg: typeof import('bootstrap-vue-next/components/BImg')['BImg']
    BModal: typeof import('bootstrap-vue-next/components/BModal')['BModal']
    BPagination: typeof import('bootstrap-vue-next/components/BPagination')['BPagination']
    BRow: typeof import('bootstrap-vue-next/components/BContainer')['BRow']
    BTab: typeof import('bootstrap-vue-next/components/BTabs')['BTab']
    BTable: typeof import('bootstrap-vue-next/components/BTable')['BTable']
    BTabs: typeof import('bootstrap-vue-next/components/BTabs')['BTabs']
    ConfirmationModal: typeof import('./src/components/ConfirmationModal.vue')['default']
    copy: typeof import('./src/components/CopyList copy.vue')['default']
    CopyList: typeof import('./src/components/CopyList.vue')['default']
    CopyManager: typeof import('./src/components/CopyManager.vue')['default']
    Dashboard: typeof import('./src/components/Dashboard.vue')['default']
    DownloadCopyList: typeof import('./src/components/DownloadCopyList.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ImageSelectionModal: typeof import('./src/components/ImageSelectionModal.vue')['default']
    LoadingButton: typeof import('./src/components/LoadingButton.vue')['default']
    LoadingLink: typeof import('./src/components/LoadingLink.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    Logs: typeof import('./src/components/Logs.vue')['default']
    Main: typeof import('./src/components/Main.vue')['default']
    PaginatedTable: typeof import('./src/components/PaginatedTable.vue')['default']
    ResourceGrid: typeof import('./src/components/ResourceGrid.vue')['default']
    ResourceManager: typeof import('./src/components/ResourceManager.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./src/components/Settings.vue')['default']
    VideoList: typeof import('./src/components/VideoList.vue')['default']
    VideoManager: typeof import('./src/components/VideoManager.vue')['default']
    VideoModal: typeof import('./src/components/VideoModal.vue')['default']
  }
}
